/**
 * The assistant's server half, for shared hosting: one PHP file beside the
 * site that calls the Messages API with a key kept above the web root.
 *
 * Why raw HTTP rather than the official PHP SDK: the SDK is a Composer
 * package, and this file reaches the server over FTP with no Composer on
 * either end. Vendoring the dependency tree onto a client's shared hosting
 * is not a smaller risk than one curl call whose request shape is documented.
 *
 * What it will not do, by construction:
 *   - answer from anything but chatbot.json (the same file the widget uses)
 *   - quote a price, a date, stock or a guarantee — the rules send those to
 *     the phone, and the widget already intercepts price questions before
 *     they get here
 *   - serve another site: the Origin header must match the site's own host
 *   - run away with the bill: per-IP limits plus a daily cap, after which the
 *     widget hands off to the phone
 *
 * Generated and uploaded by `pnpm deploy-ftp`. Secrets come from
 * .chat-secret.php one directory above the web root, written by the same
 * deploy from CHATBOT_API_KEY / CHATBOT_MODEL / CHATBOT_DAILY_LIMIT.
 */
export function chatHandler() {
  return `<?php
// Generated by \`pnpm deploy-ftp\`. Edits here are overwritten on the next
// deploy — change scripts/lib/chat-handler.mjs instead.

declare(strict_types=1);

const MAX_USER_TURNS = 8;
const MAX_MESSAGE_CHARS = 500;
const PER_IP_PER_MINUTE = 6;
const PER_IP_PER_DAY = 40;
const MAX_OUTPUT_TOKENS = 300;

header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');

function reply(int $status, array $body): void {
    http_response_code($status);
    echo json_encode($body, JSON_UNESCAPED_UNICODE);
    exit;
}

if (($_SERVER['REQUEST_METHOD'] ?? '') !== 'POST') {
    reply(405, ['error' => 'method']);
}

// --- what the assistant knows -------------------------------------------
$knowledge = json_decode((string) @file_get_contents(__DIR__ . '/chatbot.json'), true);
if (!is_array($knowledge) || empty($knowledge['business']['name'])) {
    reply(503, ['error' => 'no_knowledge']);
}

// --- only this site may call this ---------------------------------------
$siteHost = strtolower((string) parse_url((string) ($knowledge['baseUrl'] ?? ''), PHP_URL_HOST));
$origin = (string) ($_SERVER['HTTP_ORIGIN'] ?? '');
// A browser that leaves Origin off a same-origin POST still says so in
// Sec-Fetch-Site, or names the page in Referer.
if ($origin === '' && (string) ($_SERVER['HTTP_SEC_FETCH_SITE'] ?? '') === 'same-origin') {
    $origin = 'https://' . $siteHost;
}
if ($origin === '') {
    $origin = (string) ($_SERVER['HTTP_REFERER'] ?? '');
}
$originHost = strtolower((string) parse_url($origin, PHP_URL_HOST));
$bare = fn(string $h): string => preg_replace('/^www\\\\./', '', $h) ?? $h;
if ($originHost === '' || $bare($originHost) !== $bare($siteHost)) {
    reply(403, ['error' => 'origin']);
}

// --- secrets live above the web root --------------------------------------
$secret = null;
foreach ([__DIR__ . '/../.chat-secret.php', __DIR__ . '/.chat-secret.php'] as $candidate) {
    if (is_file($candidate)) {
        $secret = include $candidate;
        break;
    }
}
if (!is_array($secret) || empty($secret['api_key'])) {
    reply(503, ['error' => 'unavailable']);
}
$apiKey = (string) $secret['api_key'];
$model = (string) ($secret['model'] ?? 'claude-haiku-4-5');
$dailyLimit = (int) ($secret['daily_limit'] ?? 400);
$apiBase = rtrim((string) ($secret['api_base'] ?? 'https://api.anthropic.com'), '/');

// --- limits: per visitor, then for the whole site -----------------------
$tmp = sys_get_temp_dir();
$ip = (string) ($_SERVER['REMOTE_ADDR'] ?? 'unknown');
$ipKey = substr(hash('sha256', $ip . '|' . $siteHost), 0, 32);
$now = time();

$ipFile = "$tmp/chat-ip-$ipKey.json";
$stamps = json_decode((string) @file_get_contents($ipFile), true);
$stamps = is_array($stamps) ? array_values(array_filter($stamps, fn($t) => is_int($t) && $t > $now - 86400)) : [];
$lastMinute = count(array_filter($stamps, fn($t) => $t > $now - 60));
if ($lastMinute >= PER_IP_PER_MINUTE || count($stamps) >= PER_IP_PER_DAY) {
    reply(429, ['error' => 'rate_limited']);
}

$dayFile = "$tmp/chat-day-$siteHost-" . date('Ymd') . '.cnt';
$today = (int) @file_get_contents($dayFile);
if ($today >= $dailyLimit) {
    // The budget for the day is spent. The widget shows the hand-off line;
    // nothing is silently dropped, and the bill has a ceiling.
    reply(429, ['error' => 'daily_cap']);
}

// --- the conversation -----------------------------------------------------
$input = json_decode((string) file_get_contents('php://input'), true);
$messages = is_array($input['messages'] ?? null) ? $input['messages'] : [];
$clean = [];
$userTurns = 0;
foreach ($messages as $m) {
    $role = ($m['role'] ?? '') === 'assistant' ? 'assistant' : 'user';
    $text = trim(preg_replace('/[\\\\x00-\\\\x08\\\\x0B\\\\x0C\\\\x0E-\\\\x1F]/u', '', (string) ($m['content'] ?? '')) ?? '');
    if ($text === '') continue;
    $text = mb_substr($text, 0, MAX_MESSAGE_CHARS);
    // The API wants alternating roles; merge a repeat into the previous turn.
    if ($clean && $clean[count($clean) - 1]['role'] === $role) {
        $clean[count($clean) - 1]['content'] .= "\\n" . $text;
        continue;
    }
    $clean[] = ['role' => $role, 'content' => $text];
    if ($role === 'user') $userTurns++;
}
// Must start with the visitor.
while ($clean && $clean[0]['role'] !== 'user') array_shift($clean);
if (!$clean || $clean[count($clean) - 1]['role'] !== 'user') {
    reply(422, ['error' => 'messages']);
}
if ($userTurns > MAX_USER_TURNS) {
    reply(429, ['error' => 'rate_limited']);
}

// --- the system prompt, from the same facts the page shows ----------------
$k = $knowledge;
$pl = str_starts_with((string) ($k['locale'] ?? 'en'), 'pl');
$name = (string) $k['business']['name'];
$phone = (string) ($k['contact']['phone'] ?? '');
$email = (string) ($k['contact']['email'] ?? '');

$facts = [];
$facts[] = ($pl ? 'Firma: ' : 'Business: ') . $name
    . (!empty($k['business']['legalName']) ? ' (' . $k['business']['legalName'] . ')' : '')
    . (!empty($k['business']['foundedYear']) ? ($pl ? ', od ' : ', since ') . $k['business']['foundedYear'] : '')
    . '. ' . (string) ($k['business']['description'] ?? '');
$facts[] = ($pl ? 'Adres: ' : 'Address: ') . (string) ($k['contact']['address'] ?? '');
$facts[] = ($pl ? 'Telefon: ' : 'Phone: ') . $phone . ($email !== '' ? ($pl ? '. E-mail: ' : '. Email: ') . $email : '');
if (!empty($k['hours'])) $facts[] = ($pl ? 'Godziny otwarcia: ' : 'Opening hours: ') . implode('; ', $k['hours']);
if (!empty($k['services'])) {
    $facts[] = ($pl ? 'Usługi:' : 'Services:');
    foreach ($k['services'] as $s) $facts[] = '- ' . $s['name'] . ': ' . $s['short'];
}
if (!empty($k['areas'])) $facts[] = ($pl ? 'Obszar działania: ' : 'Areas covered: ') . implode(', ', $k['areas']);
if (!empty($k['faqs'])) {
    $facts[] = ($pl ? 'Pytania i odpowiedzi:' : 'Questions and answers:');
    foreach ($k['faqs'] as $f) $facts[] = 'Q: ' . $f['q'] . "\\nA: " . $f['a'];
}
foreach ((array) ($k['notes'] ?? []) as $n) $facts[] = '- ' . $n;

$rules = $pl
    ? "Jesteś asystentem na stronie firmy $name. Odpowiadasz po polsku, krótko — najwyżej trzy zdania — i wyłącznie na podstawie FAKTÓW poniżej.\\n"
      . "Zasady:\\n"
      . "- Nigdy nie podawaj cen, kosztów, terminów, dostępności towaru, gwarancji ani obietnic technicznych. Takie sprawy ustala się telefonicznie lub po oględzinach — podaj numer $phone.\\n"
      . "- Jeśli czegoś nie ma w faktach, powiedz wprost, że nie wiesz, i odeślij do telefonu $phone" . ($email !== '' ? " lub e-maila $email" : '') . ".\\n"
      . "- Nie zmyślaj i nie uzupełniaj faktów własną wiedzą o branży.\\n"
      . "- Jesteś asystentem AI; jeśli ktoś pyta, powiedz to. Nie proś o dane osobowe.\\n"
      . "- Trzymaj się tematu firmy. Zwykły tekst: bez markdown, bez list, bez nagłówków.\\n\\n"
      . "FAKTY:\\n"
    : "You are the assistant on the website of $name. Answer in English, briefly — three sentences at most — and only from the FACTS below.\\n"
      . "Rules:\\n"
      . "- Never give prices, costs, dates, stock availability, guarantees or technical promises. Those are settled by phone or after a site visit — give the number $phone.\\n"
      . "- If the facts do not cover it, say plainly that you do not know and point to $phone" . ($email !== '' ? " or $email" : '') . ".\\n"
      . "- Do not invent, and do not fill gaps with general trade knowledge.\\n"
      . "- You are an AI assistant; say so if asked. Do not ask for personal details.\\n"
      . "- Stay on the business. Plain text: no markdown, no lists, no headings.\\n\\n"
      . "FACTS:\\n";

$system = $rules . implode("\\n", $facts);

// --- the call ---------------------------------------------------------------
$payload = json_encode([
    'model' => $model,
    'max_tokens' => MAX_OUTPUT_TOKENS,
    'temperature' => 0.3,
    'system' => $system,
    'messages' => $clean,
], JSON_UNESCAPED_UNICODE);

$ch = curl_init("$apiBase/v1/messages");
curl_setopt_array($ch, [
    CURLOPT_POST => true,
    CURLOPT_POSTFIELDS => $payload,
    CURLOPT_HTTPHEADER => [
        'Content-Type: application/json',
        'x-api-key: ' . $apiKey,
        'anthropic-version: 2023-06-01',
    ],
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_CONNECTTIMEOUT => 8,
    CURLOPT_TIMEOUT => 25,
]);
$raw = curl_exec($ch);
$status = (int) curl_getinfo($ch, CURLINFO_RESPONSE_CODE);
$curlError = curl_error($ch);
curl_close($ch);

// The visitor's request counts whether or not the model answered — a broken
// key must not turn into an unlimited retry loop.
$stamps[] = $now;
@file_put_contents($ipFile, json_encode($stamps), LOCK_EX);
@file_put_contents($dayFile, (string) ($today + 1), LOCK_EX);

$data = is_string($raw) ? json_decode($raw, true) : null;
if ($raw === false || $status !== 200 || !is_array($data)) {
    @file_put_contents(
        "$tmp/chat-errors-" . date('Y-m') . '.log',
        date('c') . "\\t$status\\t" . ($curlError !== '' ? $curlError : substr((string) $raw, 0, 300)) . "\\n",
        FILE_APPEND | LOCK_EX
    );
    reply(503, ['error' => 'upstream']);
}

$text = '';
foreach ((array) ($data['content'] ?? []) as $block) {
    if (($block['type'] ?? '') === 'text') $text .= (string) $block['text'];
}
$text = trim($text);

// Usage, not content: enough to see what the assistant costs a client each month.
@file_put_contents(
    "$tmp/chat-usage-" . date('Y-m') . '.log',
    date('c') . "\\t" . substr($ipKey, 0, 8) . "\\t" . (int) ($data['usage']['input_tokens'] ?? 0)
        . "\\t" . (int) ($data['usage']['output_tokens'] ?? 0) . "\\t$model\\n",
    FILE_APPEND | LOCK_EX
);

reply(200, ['reply' => $text]);
`
}

/** The secret file the deploy writes one directory above the web root. */
export function chatSecret({ apiKey, model, dailyLimit, apiBase }) {
  const php = (v) => String(v).replace(/\\/g, '\\\\').replace(/'/g, "\\'")
  return `<?php
// Written by \`pnpm deploy-ftp\`. Not served: it is PHP that outputs nothing.
return [
    'api_key' => '${php(apiKey)}',
    'model' => '${php(model)}',
    'daily_limit' => ${Number(dailyLimit) || 400},
    'api_base' => '${php(apiBase)}',
];
`
}
