/**
 * A contact-form endpoint for shared hosting, generated from the build.
 *
 * A static site has nowhere to post a form, so the template's default is a
 * third-party endpoint (Web3Forms, Formspree, an n8n webhook). When the site
 * lands on the client's own PHP hosting there is a better answer: the same
 * machine that serves the pages also runs their mail. No third-party account,
 * no monthly fee, no data leaving their host — and mail sent from there
 * already passes their SPF record, because the sending IP is the one their
 * SPF names.
 *
 * Generated and uploaded by `pnpm deploy-ftp` when the build posts to
 * form.php. Set `forms.endpoint: '/form.php'` in the client's config.
 */
export function formHandler({ to, siteName, subject }) {
  const php = (value) => String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")

  return `<?php
// Generated by \`pnpm deploy-ftp\`. Edits here are overwritten on the next
// deploy — change scripts/lib/form-handler.mjs instead.

declare(strict_types=1);

const RECIPIENT = '${php(to)}';
const SITE_NAME = '${php(siteName)}';
const SUBJECT   = '${php(subject)}';
const THROTTLE_SECONDS = 20;

header('Content-Type: application/json; charset=utf-8');

function reject(int $status, string $message): void {
    http_response_code($status);
    echo json_encode(['ok' => false, 'error' => $message], JSON_UNESCAPED_UNICODE);
    exit;
}

if (($_SERVER['REQUEST_METHOD'] ?? '') !== 'POST') {
    reject(405, 'Method not allowed');
}

// Honeypot: a real visitor never fills a field they cannot see. Answer 200 so
// the bot has nothing to learn from the response.
if (trim((string) ($_POST['company'] ?? '')) !== '') {
    echo json_encode(['ok' => true], JSON_UNESCAPED_UNICODE);
    exit;
}

$ip = (string) ($_SERVER['REMOTE_ADDR'] ?? 'unknown');
$stamp = sys_get_temp_dir() . '/form-' . hash('sha256', $ip) . '.txt';
if (is_file($stamp) && (time() - (int) filemtime($stamp)) < THROTTLE_SECONDS) {
    reject(429, 'Too many requests');
}

/** Header fields must never carry a newline — that is how headers get injected. */
function single_line(string $value, int $limit): string {
    $value = str_replace(["\\r", "\\n", "\\0"], ' ', $value);
    return trim(mb_substr($value, 0, $limit));
}

$name    = single_line((string) ($_POST['name'] ?? ''), 120);
$phone   = single_line((string) ($_POST['phone'] ?? ''), 40);
$email   = single_line((string) ($_POST['email'] ?? ''), 160);
$service = single_line((string) ($_POST['service'] ?? ''), 120);
$message = trim(mb_substr((string) ($_POST['message'] ?? ''), 0, 5000));

if ($name === '' || $phone === '' || $message === '') {
    reject(422, 'Missing required fields');
}
if ($email !== '' && !filter_var($email, FILTER_VALIDATE_EMAIL)) {
    reject(422, 'Invalid email');
}

$body = "Nowe zapytanie ze strony " . SITE_NAME . "\\n\\n"
    . "Imię i nazwisko: {$name}\\n"
    . "Telefon: {$phone}\\n"
    . "E-mail: " . ($email !== '' ? $email : '—') . "\\n"
    . "Usługa: " . ($service !== '' ? $service : '—') . "\\n\\n"
    . "Wiadomość:\\n{$message}\\n\\n"
    . "---\\n"
    . "Wysłane " . date('Y-m-d H:i:s') . " z formularza na " . SITE_NAME . "\\n";

// From must be an address on this domain or the host's mail server refuses it
// and SPF fails; the visitor's address goes in Reply-To, where it belongs.
$headers = [
    'From: ' . SITE_NAME . ' <' . RECIPIENT . '>',
    'Content-Type: text/plain; charset=UTF-8',
    'X-Mailer: PHP/' . phpversion(),
];
if ($email !== '') {
    $headers[] = 'Reply-To: ' . $email;
}

// Only a submission that is actually being sent counts against the throttle.
@touch($stamp);

$sent = @mail(RECIPIENT, SUBJECT, $body, implode("\\r\\n", $headers), '-f' . RECIPIENT);

if (!$sent) {
    // Losing a real enquiry silently is the worst outcome, so leave a trace
    // the operator can recover from — outside the web root, because it holds
    // the sender's name, phone number and email address.
    @file_put_contents(
        sys_get_temp_dir() . '/form-failed-' . date('Y-m') . '.log',
        $body . "\\n====\\n",
        FILE_APPEND | LOCK_EX
    );
    reject(500, 'Mail delivery failed');
}

echo json_encode(['ok' => true], JSON_UNESCAPED_UNICODE);
`
}
