/**
 * Apache/LiteSpeed config for the static export on shared hosting.
 *
 * Three of these rules are load-bearing rather than nice-to-have:
 *
 *   DirectoryIndex   A site replacing WordPress shares the directory with a
 *                    leftover index.php until someone clears it. Apache serves
 *                    whichever it finds first, so index.html has to be named
 *                    ahead of it or the old site keeps winning.
 *   DEFLATE          Auditing against an uncompressed server reported ~20
 *                    Lighthouse points low (DECISIONS.md, performance
 *                    findings). Shared hosts do not all enable it by default.
 *   Cache-Control    Everything under /_next/static is content-hashed and can
 *                    be immutable for a year; HTML must not be, or a client's
 *                    edit sits invisible behind a stale cache.
 */
export function htaccess({ baseUrl }) {
  const host = new URL(baseUrl).host
  const wwwIsCanonical = host.startsWith('www.')
  const bare = wwwIsCanonical ? host.slice(4) : host

  const canonicalHost = wwwIsCanonical
    ? `  # Canonical host: www
  RewriteCond %{HTTP_HOST} ^${bare.replace(/\./g, '\\.')}$ [NC]
  RewriteRule ^(.*)$ https://${host}/$1 [R=301,L]`
    : `  # Canonical host: no www
  RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]
  RewriteRule ^(.*)$ https://%1/$1 [R=301,L]`

  return `# Generated by \`pnpm deploy-ftp\`. Edits made on the server are overwritten
# on the next deploy — change scripts/lib/htaccess.mjs instead.

DirectoryIndex index.html index.php
Options -Indexes
ErrorDocument 404 /404.html

<IfModule mod_rewrite.c>
  RewriteEngine On

  # HTTPS first, so the canonical-host redirect below never sends a visitor
  # through a second hop.
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP:X-Forwarded-Proto} !https
  RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [R=301,L]

${canonicalHost}
</IfModule>

<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/plain text/css text/xml
  AddOutputFilterByType DEFLATE application/javascript application/json
  AddOutputFilterByType DEFLATE application/xml image/svg+xml
</IfModule>

<IfModule mod_headers.c>
  # Content-hashed build output: safe to keep forever.
  <If "%{REQUEST_URI} =~ m#^/_next/static/#">
    Header set Cache-Control "public, max-age=31536000, immutable"
  </If>

  # Imagery and fonts change under a new name when they change at all.
  <FilesMatch "\\.(webp|avif|jpg|jpeg|png|gif|svg|ico|woff2?)$">
    Header set Cache-Control "public, max-age=2592000"
  </FilesMatch>

  # Pages must revalidate, or a retainer edit is invisible to anyone who
  # visited before it.
  <FilesMatch "\\.(html|xml|txt|json)$">
    Header set Cache-Control "public, max-age=0, must-revalidate"
  </FilesMatch>

  Header set X-Content-Type-Options "nosniff"
  Header set Referrer-Policy "strict-origin-when-cross-origin"
  Header set X-Frame-Options "SAMEORIGIN"
</IfModule>

<IfModule mod_mime.c>
  AddType image/webp .webp
  AddType image/avif .avif
  AddType font/woff2 .woff2
</IfModule>
`
}
